### ISSUE TITLE
How can I use it on my own data set?

### ISSUE THREAD

**Issue by 18222why** [CeMOS-IS/GenFormer#2]

**Comment by OehriSven** [comment]
Hi @18222why,

to apply GenFormer to your dataset you will have to train a generative model (e.g. Diffusion) on your own dataset (see [Data Generation](https://github.com/CeMOS-IS/GenFormer/tree/main?tab=readme-ov-file#data-generation)) and generate synthetic samples of your data. You will then have to place your generated dataset according to the structure shown in [Data preparation](https://github.com/CeMOS-IS/GenFormer/tree/main?tab=readme-ov-file#data-preparation). I hope this answers your question.
